from pydantic import BaseModel, EmailStr, Field
from typing import Optional
from datetime import datetime, date as date_, time
from enum import Enum


# ─────────────────────────────────────────────
#  ENUMS
# ─────────────────────────────────────────────

class TaskCategory(str, Enum):
    work    = "work"
    school  = "school"
    network = "network"
    hobby   = "hobby"
    errand  = "errand"

class TaskStatus(str, Enum):
    pending   = "pending"
    complete  = "complete"
    rolled    = "rolled"    # carried over from a previous day
    dropped   = "dropped"   # optional task removed after delinquency threshold

class TaskSource(str, Enum):
    planner  = "planner"   # generated by the LLM
    email    = "email"     # surfaced from a flagged email
    manual   = "manual"    # user added it themselves via the drawer
    rollover = "rollover"  # was pending, carried from a previous day

class ContactStatus(str, Enum):
    target         = "target"          # identified, not yet reached out
    reached_out    = "reached_out"     # message sent, no reply
    waiting        = "waiting"         # follow-up sent, still waiting
    replied        = "replied"         # they responded
    met            = "met"             # had a real conversation / coffee chat
    not_interested = "not_interested"

class EmailActionType(str, Enum):
    reply_needed     = "reply_needed"
    follow_up        = "follow_up"
    schedule_meeting = "schedule_meeting"
    none             = "none"

class EventType(str, Enum):
    shift   = "shift"    # work shift
    class_  = "class"    # lecture, lab, section
    meeting = "meeting"  # any scheduled meeting
    other   = "other"    # catch-all (appointment, event, etc.)


# ─────────────────────────────────────────────
#  INNER OBJECTS
# ─────────────────────────────────────────────

class EmailSender(BaseModel):
    """Who sent the email — broken out so we can cross-reference against contacts"""
    name:       Optional[str] = None
    address:    str                         # raw email address
    contact_id: Optional[int] = None        # FK → Contact.id if we recognize them


class TimeWindow(BaseModel):
    """A start/end time pair — reused across CalendarEvent and DayLog"""
    start: datetime
    end:   Optional[datetime] = None        # None means still in progress

    @property
    def duration_minutes(self) -> Optional[int]:
        if self.end is None:
            return None
        return int((self.end - self.start).total_seconds() / 60)


class ContactHistory(BaseModel):
    """A single interaction with a contact — stored as a list on Contact"""
    date:    datetime
    method:  str            # "email" | "linkedin" | "text" | "call" | "in_person"
    notes:   Optional[str] = None
    task_id: Optional[int] = None   # FK → Task.id if this came from a task


# ─────────────────────────────────────────────
#  CORE MODELS
# ─────────────────────────────────────────────

class Task(BaseModel):
    id:               Optional[int] = None
    title:            str
    category:         TaskCategory
    status:           TaskStatus    = TaskStatus.pending
    duration_minutes: int           = 30
    priority:         int           = 3             # 1 (highest) → 5 (lowest)
    is_optional:      bool          = False
    rolled_over_count: int          = 0             # how many days this has been carried

    # ── new fields ──────────────────────────────
    due_date: Optional[date_] = None
    # None = no hard deadline; set by planner or user
    # The planner should treat tasks with due_date == today as priority 1 automatically.

    source: TaskSource = TaskSource.manual
    # Tracks provenance: did the LLM suggest this? Did an email trigger it?
    # Rollover logic should set source = "rollover" when carrying a task forward.
    # ────────────────────────────────────────────

    created_date:   date_              = Field(default_factory=date_.today)
    completed_date: Optional[datetime] = None

    # optional linkage
    linked_contact_id: Optional[int] = None   # FK → Contact.id  (e.g. "reach out to Jake")
    linked_event_id:   Optional[int] = None   # FK → CalendarEvent.id (replaces linked_shift_id)
    notes:             Optional[str] = None


class CalendarEvent(BaseModel):
    """
    A block of time that cannot be moved or completed — it just exists.
    The planner must load all CalendarEvents for today before scheduling any tasks.
    Tasks should never be scheduled inside an event's window.

    Sources: imported from .ics, synced from Google Calendar, or entered manually.
    """
    id:         Optional[int] = None
    title:      str
    event_type: EventType

    window: TimeWindow          # start + end — both required for events (unlike DayLog)

    location:   Optional[str] = None
    notes:      Optional[str] = None
    is_recurring: bool = False  # True if this repeats (e.g. MWF class, weekly shift)

    # linkage — a CalendarEvent can relate to a contact (e.g. a coffee chat meeting)
    linked_contact_id: Optional[int] = None  # FK → Contact.id

    # source provenance
    ical_uid:   Optional[str] = None  # uid from .ics import — used for dedup
    gcal_id:    Optional[str] = None  # Google Calendar event id, for future OAuth sync

    @property
    def duration_minutes(self) -> Optional[int]:
        return self.window.duration_minutes

    @property
    def date(self) -> date_:
        return self.window.start.date()


class Contact(BaseModel):
    id:      Optional[int] = None
    name:    str
    company: Optional[str] = None
    role:    Optional[str] = None
    status:  ContactStatus = ContactStatus.target

    # ways to reach them
    email:        Optional[str] = None
    linkedin_url: Optional[str] = None
    phone:        Optional[str] = None

    # context
    source: Optional[str] = None   # "linkedin" | "referral" | "event" | "cold"
    notes:  Optional[str] = None
    tags:   list[str]     = []     # e.g. ["fintech", "swe", "alumni"]

    # history — each element is a ContactHistory object
    interactions:   list[ContactHistory] = []
    last_contacted: Optional[datetime]   = None  # cached from interactions

    @property
    def times_contacted(self) -> int:
        return len(self.interactions)


class Email(BaseModel):
    id:           Optional[int] = None
    account:      str           # which inbox — e.g. "personal" | "school"
    sender:       EmailSender
    subject:      str
    body_preview: Optional[str] = None   # first ~200 chars, not the full body
    received_at:  datetime

    is_read:         bool            = False
    requires_action: bool            = False
    action_type:     EmailActionType = EmailActionType.none

    # linkage
    linked_contact_id: Optional[int] = None   # FK → Contact.id
    linked_task_id:    Optional[int] = None   # FK → Task.id


class WorkShift(BaseModel):
    """
    Deprecated in favor of CalendarEvent(event_type='shift').
    Kept temporarily so existing DB rows and service code don't break.
    Migration path: backfill WorkShift rows into CalendarEvent, then drop this table.
    """
    id:       Optional[int] = None
    date:     date_
    window:   TimeWindow
    location: Optional[str] = None
    notes:    Optional[str] = None

    @property
    def duration_minutes(self) -> Optional[int]:
        return self.window.duration_minutes


class DayLog(BaseModel):
    id:     Optional[int] = None
    date:   date_          = Field(default_factory=date_.today)
    window: TimeWindow

    # snapshot at EOD
    tasks_completed:   int = 0
    tasks_rolled_over: int = 0
    tasks_dropped:     int = 0

    # the raw list of task IDs touched today
    completed_task_ids:   list[int] = []
    rolled_over_task_ids: list[int] = []

    notes: Optional[str] = None   # freeform EOD note